TA-563-Admit Part Of the claim scenarios
hmcts/cmc-citizen-frontend pull request #2935
Opened 2021-03-16 11:39 UTC by phaniperla

### JIRA link
https://tools.hmcts.net/jira/browse/TA-564
https://tools.hmcts.net/jira/browse/TA-563
https://tools.hmcts.net/jira/browse/TA-566

### Change description

1. Admit part of the claim scenarios
2. Admit all of the claim scenarios
3. Test code improvements

### Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

2021-03-16 16:34 UTC, pradhap87 commented
Closed this PR for freeing up memory in the pipeline. PLease reopen the PR tomorrow

2021-03-17 08:48 UTC, zakishaik approved these changes

2021-03-17 08:50 UTC, pradhap87 requested changes
@phaniperla why are are you adding @citizen for the test cases. This is increase the master build timing. Some of the test cases are only intended to run in nightly build. Can we have review of all of your changes (just only nightly test cases which you have added @citizen).

@yogendraU @sunilkumar-cts

2021-03-17 08:59 UTC, pradhap87 approved these changes

2021-03-17 09:01 UTC, pradhap87 commented
We can keep this as-is for now, it will help us to see why some testes are not passing in nightly

2021-03-18 16:25 UTC, closed without merging