TA-561-I have paid what i believe i owe E2E
hmcts/cmc-citizen-frontend pull request #2939
Opened 2021-03-16 13:12 UTC by phaniperla

### JIRA link

https://tools.hmcts.net/jira/browse/TA-567
https://tools.hmcts.net/jira/browse/TA-561

### Change description

1. I have paid what i believe i owe

### Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

2021-03-16 16:34 UTC, pradhap87 commented
Closed this PR for freeing up memory in the pipeline. PLease reopen the PR tomorrow

2021-03-17 08:21 UTC, zakishaik approved these changes

2021-03-17 09:06 UTC, pradhap87 requested changes
Build is failing, there is some lint issue in your code. Can you fix then and re-request the review.

2021-03-17 09:07 UTC, pradhap87 commented
![image](https://user-images.githubusercontent.com/41957682/111442419-40b0a400-8700-11eb-8cee-6c06838abb1a.png)

2021-03-19 07:53 UTC, closed without merging