Automation/roc 9042 breathing space
hmcts/cmc-citizen-frontend pull request #3026
Opened 2021-04-22 13:36 UTC by zakishaik

### JIRA link

https://tools.hmcts.net/jira/browse/ROC-9042

### Change description

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled 
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent 

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

2021-04-27 09:58 UTC, pradhap87 approved these changes

2021-04-27 10:19 UTC, pradhap87 requested changes

2021-04-27 10:19 UTC, pradhap87 commented on src/integration-test/tests/citizen/breathing-space/breathingspace_test.ts
> +Scenario('Claimant can enter and lift the Breathing space @smoke @nightly', { retries: 3 }, async (I: I) => {
It must be @smoke-test
```suggestion
Scenario('Claimant can enter and lift the Breathing space @smoke-test @nightly', { retries: 3 }, async (I: I) => {
```

2021-04-27 10:21 UTC, pradhap87 approved these changes

2021-05-10 15:01 UTC, yogendraU approved these changes

2021-06-16 19:30 UTC, closed without merging